#!/bin/bash

set -ex

run-with () {
  exercise=$1
  command=$2

  echo "Running exercise $exercise"
  $command $exercise &
  PID=$!

  EXERCISE=$exercise npx mocha test-runner-node.js || {
    echo "Test failed"
    kill -9 $PID
    exit 1
  }

  kill -9 $PID
}

run-node () {
  echo "Running with node"
  run-with $1 "node index.js"
}

run-hs () {
  echo "Running with Haskell"
  run-with $1 "stack exec exercises --"
}

run () {
  run-node $1
  run-hs $1
}


stack build --fast

run 01
run 02
run 03
run 04
run 05
run 06
run 07
run 08