#!/bin/bash

set -ex

cd exercises

run-with () {
  # $1: ex number
  # $2: program (ie. node index.js)

  echo "Running exercise $1"
  $2 $1 &
  PID=$!

  EXERCISE=$1 npx mocha test-runner.js || {
    echo "Test failed"
    kill -9 $PID
    exit 1
  }

  kill -9 $PID
}

run-node () {
  echo "Running with node"
  run-with $1 "node index.js"
}

run-hs () {
  echo "Running with Haskell"
  run-with $1 "stack exec exercises --"
}

run () {
  run-node $1
  run-hs $1
}


stack build --fast

run 1
run 2
run 3
